trigger: none

pr:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- script: docker build . --file ci.Dockerfile --tag jaxexamples:$(date +%s)
  displayName: 'Build: CI Container'
  
