trigger:
- main

pr:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- script: curl -sSL https://install.python-poetry.org | python3 - 
  displayName: 'Install: Poetry'
- script: poetry config virtualenvs.create false && poetry install
  displayName: 'Install: Dependencies'
- script: JAX_PLATFORMS=cpu poetry run sanity_check
  displayName: 'Check: Jax Array Creation'
- script: docker build . --file devcontainer.Dockerfile --tag experiments:$(date +%s)
  displayName: 'Build: Dev Container'
  
